name: CI
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix:
        python-version: [3.6]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install scikit-image opencv-python lmdb h5py pyarrow
          python -m pip install .
          python -c "import cv2; print('OpenCV '+ cv2.__version__)"
      - name: Install TF
        env:
          TF_VERSION: ${{ matrix.TF-version }}
        run: |
          python -m pip install tensorflow
          python -c "import tensorflow as tf; print(tf.VERSION, tf.GIT_VERSION)"
